project:
  name: quickstart-mongodb-atlas
  owner: quickstart-eng@amazon.com
  package_lambda: true
  regions:
  - us-east-1
  s3_bucket: ''
  #QSS3BucketName: $[taskcat_autobucket]
  #QSS3BucketRegion: $[taskcat_current_region]
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  shorten_stack_name: true
tests:
  mongodb-atlas:
    parameters:
      PublicKey: override
      PrivateKey: override
      OrgId: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      #RemoteAccessCIDR: 10.0.0.0/16
    s3_bucket: ''
    template: templates/mongodb-atlas-main.template.yaml
  mongodb-atlas-peering:
    parameters:
      PublicKey: override
      PrivateKey: override
      OrgId: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RouteTableCIDRBlock: 10.0.0.0/16
      AvailabilityZones: $[taskcat_genaz_2]
      #RemoteAccessCIDR: 10.0.0.0/16
    s3_bucket: ''
    template: templates/mongodb-atlas-peering-newvpc.template.yaml

